package com.nanotate.dao.model;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user.username
     *
     * @mbggenerated Tue Apr 22 02:16:40 COT 2014
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user.password
     *
     * @mbggenerated Tue Apr 22 02:16:40 COT 2014
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user.username
     *
     * @return the value of public.user.username
     *
     * @mbggenerated Tue Apr 22 02:16:40 COT 2014
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user.username
     *
     * @param username the value for public.user.username
     *
     * @mbggenerated Tue Apr 22 02:16:40 COT 2014
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user.password
     *
     * @return the value of public.user.password
     *
     * @mbggenerated Tue Apr 22 02:16:40 COT 2014
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user.password
     *
     * @param password the value for public.user.password
     *
     * @mbggenerated Tue Apr 22 02:16:40 COT 2014
     */
    public void setPassword(String password) {
        this.password = password;
    }
}