package org.nanotate.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.server.ExternalResource;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Embedded;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;

public class Home extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Panel panel_4;
	@AutoGenerated
	private AbsoluteLayout absoluteLayout_4;
	@AutoGenerated
	private Embedded embedded_2;
	/**
	 * 
	 */
	private static final long serialVersionUID = 2380899407168549005L;

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public Home() {
	
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// panel_4
		panel_4 = buildPanel_4();
		mainLayout.addComponent(panel_4);
		mainLayout.setComponentAlignment(panel_4, new Alignment(20));
		
		return mainLayout;
	}

	@AutoGenerated
	private Panel buildPanel_4() {
		// common part: create layout
		panel_4 = new Panel();
		panel_4.setImmediate(false);
		panel_4.setWidth("90.0%");
		panel_4.setHeight("100.0%");
		
		// absoluteLayout_4
		absoluteLayout_4 = buildAbsoluteLayout_4();
		panel_4.setContent(absoluteLayout_4);
		
		return panel_4;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsoluteLayout_4() {
		// common part: create layout
		absoluteLayout_4 = new AbsoluteLayout();
		absoluteLayout_4.setImmediate(false);
		absoluteLayout_4.setWidth("900.0%");
		absoluteLayout_4.setHeight("100.0%");
		
		// embedded_2
		embedded_2 = new Embedded();
		embedded_2.setStyleName("largest-profile-pic");
		embedded_2.setImmediate(false);
		embedded_2.setWidth("-1px");
		embedded_2.setHeight("-1px");
		embedded_2.setType(1);
		embedded_2.setMimeType("image/png");
		absoluteLayout_4.addComponent(embedded_2, "top:50.0px;left:100.0px;");
		
		return absoluteLayout_4;
	}
	
	public void setImageURL(String url){
		embedded_2
		.setSource(new ExternalResource(url));
	}

}
