package org.nanotate.ui;

import org.nanotate.ui.components.TwitterButton;
import org.vaadin.addon.oauthpopup.OAuthListener;
import org.vaadin.addon.oauthpopup.buttons.FacebookButton;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Notification;
import com.vaadin.ui.Panel;

public class Login extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Panel panel_2;
	@AutoGenerated
	private AbsoluteLayout absoluteLayout_2;
	@AutoGenerated
	private FacebookButton facebookButton_1;
	@AutoGenerated
	private TwitterButton twitterButton_1;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public Login() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// panel_2
		panel_2 = buildPanel_2();
		mainLayout.addComponent(panel_2, "left:0.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private Panel buildPanel_2() {
		// common part: create layout
		panel_2 = new Panel();
		panel_2.setStyleName("login-panel");
		panel_2.setImmediate(false);
		panel_2.setWidth("250px");
		panel_2.setHeight("300px");
		
		// absoluteLayout_2
		absoluteLayout_2 = buildAbsoluteLayout_2();
		panel_2.setContent(absoluteLayout_2);
		
		return panel_2;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsoluteLayout_2() {
		// common part: create layout
		absoluteLayout_2 = new AbsoluteLayout();
		absoluteLayout_2.setImmediate(false);
		absoluteLayout_2.setWidth("100.0%");
		absoluteLayout_2.setHeight("100.0%");
		
		// twitterButton_1
				twitterButton_1 = new TwitterButton("31ssXGMU4WW6KPxWwT6IMQ","FR3wJmGyGAdpQMxB3vMreED2UnsHVb6nPF16f1RrtU");
				twitterButton_1.setImmediate(false);
				twitterButton_1.setWidth("-1px");
				twitterButton_1.setHeight("-1px");
				
				
				twitterButton_1.addOAuthListener(new OAuthListener() {
					  @Override
					  public void authSuccessful(String accessToken, String accessTokenSecret) {
					    Notification.show("Authorized");
					    // TODO: do something with the access token
					  }

					  @Override
					  public void authDenied(String reason) {
					    Notification.show("Authorization denied");
					  }
					});
				
				twitterButton_1.setPopupWindowFeatures("resizable,width=400,height=300");
				
				absoluteLayout_2.addComponent(twitterButton_1,
						"top:216.0px;left:32.0px;");
				
				// facebookButton_1
				facebookButton_1 = new FacebookButton("236285369909239","df356774233762558c63281d90d21368");
				facebookButton_1.setImmediate(false);
				facebookButton_1.setWidth("-1px");
				facebookButton_1.setHeight("-1px");
				facebookButton_1.setPopupWindowFeatures("resizable,width=400,height=300");
				absoluteLayout_2.addComponent(facebookButton_1,
						"top:216.0px;right:32.0px;");
		
		return absoluteLayout_2;
	}

}
